# Generated by Django 4.0.3 on 2022-04-18 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=120)),
                ('contact_email', models.CharField(max_length=120)),
                ('contact_address', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Sold', 'Sold')], default='Active', max_length=120)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
