# Generated by Django 4.0.3 on 2022-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='static/images/user/user.png', upload_to='media/'),
        ),
    ]
